apiVersion: v1
kind: Service
metadata:
  name: iplwinpredictor-service
  namespace: himajag
spec:
  selector:
    app: iplwinpredictor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
      nodePort: 30080
  type: LoadBalancer
